// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from '@hey-api/client-fetch';
import type { HelloHiGetData, HelloHiGetResponses, GreetPersonGreetPostData, GreetPersonGreetPostResponses, GreetPersonGreetPostErrors, ResizeImageResizePostData, ResizeImageResizePostResponses, ResizeImageResizePostErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Hello
 * Simple endpoint to verify the service is running.
 */
export const helloHiGet = <ThrowOnError extends boolean = false>(options?: Options<HelloHiGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<HelloHiGetResponses, unknown, ThrowOnError>({
        url: '/hi',
        ...options
    });
};

/**
 * Greet Person
 * Greet a person by their first and last name.
 */
export const greetPersonGreetPost = <ThrowOnError extends boolean = false>(options: Options<GreetPersonGreetPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GreetPersonGreetPostResponses, GreetPersonGreetPostErrors, ThrowOnError>({
        url: '/greet',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Resize Image
 * Resize an uploaded image to the specified dimensions.
 */
export const resizeImageResizePost = <ThrowOnError extends boolean = false>(options: Options<ResizeImageResizePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ResizeImageResizePostResponses, ResizeImageResizePostErrors, ThrowOnError>({
        ...formDataBodySerializer,
        url: '/resize',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};