// This file is auto-generated by @hey-api/openapi-ts

/**
 * Body_resize_image_resize_post
 */
export type BodyResizeImageResizePost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * GreetPersonSchema
 */
export type GreetPersonSchema = {
    /**
     * First Name
     */
    first_name: string;
    /**
     * Last Name
     */
    last_name: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type HelloHiGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/hi';
};

export type HelloHiGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GreetPersonGreetPostData = {
    body: GreetPersonSchema;
    path?: never;
    query?: never;
    url: '/greet';
};

export type GreetPersonGreetPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GreetPersonGreetPostError = GreetPersonGreetPostErrors[keyof GreetPersonGreetPostErrors];

export type GreetPersonGreetPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResizeImageResizePostData = {
    body: BodyResizeImageResizePost;
    path?: never;
    query: {
        /**
         * Width
         * Target width in pixels
         */
        width: number;
        /**
         * Height
         * Target height in pixels
         */
        height: number;
    };
    url: '/resize';
};

export type ResizeImageResizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResizeImageResizePostError = ResizeImageResizePostErrors[keyof ResizeImageResizePostErrors];

export type ResizeImageResizePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};